"""Generate worker/schema.sql table + index DDL from db.py, stripping local-only tables.

Views are maintained manually in schema.sql — this script preserves them.

Usage:
    cd pipeline && python scripts/gen_schema_sql.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow importing from the pipeline package
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from generate_asset_snapshot.db import _INDEXES, _TABLES  # noqa: E402, I001
from scripts.sync_to_d1 import TABLES_TO_SYNC, _D1_COLUMNS  # noqa: E402, I001

# ── Configuration ──────────────────────────────────────────────────────────────

_SCHEMA_PATH = Path(__file__).resolve().parent.parent.parent / "worker" / "schema.sql"

_HEADER = """\
-- D1 schema for portal-api Worker
-- Auto-generated by pipeline/scripts/gen_schema_sql.py — do not edit tables/indexes by hand.
-- Views expose camelCase column names matching the TypeScript type contract.
"""

_VIEWS_MARKER = "-- ── camelCase views"

# ── Helpers ────────────────────────────────────────────────────────────────────


def _parse_create_blocks(ddl: str, keyword: str) -> list[tuple[str, str]]:
    """Split a DDL string into (object_name, full_statement) pairs.

    keyword should be 'TABLE' or 'INDEX'.
    """
    # Match CREATE TABLE/INDEX ... (...); or CREATE INDEX ... ON ...;
    pattern = rf"(CREATE\s+{keyword}\s+IF\s+NOT\s+EXISTS\s+(\w+)\s*(?:\([\s\S]*?\)|ON\s+\w+\([^)]*\))\s*;)"
    return [(m.group(2), m.group(1)) for m in re.finditer(pattern, ddl)]


def _slim_table(name: str, create_stmt: str) -> str:
    """If D1 only syncs a column subset for this table, rewrite the CREATE to match."""
    cols = _D1_COLUMNS.get(name)
    if cols is None:
        return create_stmt

    # Extract the column block between the outer parens
    m = re.search(r"\(([\s\S]+)\)", create_stmt)
    if not m:
        return create_stmt

    col_block = m.group(1)
    lines = [line.strip().rstrip(",") for line in col_block.strip().split("\n") if line.strip()]

    kept: list[str] = []
    for line in lines:
        # Match column definitions: starts with a column name
        col_match = re.match(r"(\w+)\s", line)
        if not col_match:
            # Could be a constraint like PRIMARY KEY — keep if relevant
            if line.upper().startswith("PRIMARY KEY") and "id" in cols:
                kept.append(line)
            continue
        col_name = col_match.group(1)
        if col_name == "id":
            kept.append(line)
        elif col_name in cols:
            # Strip NOT NULL DEFAULT ... to keep D1 schema lean
            kept.append(line)

    # Build the new CREATE TABLE
    col_text = ",\n  ".join(kept)
    return f"CREATE TABLE IF NOT EXISTS {name} (\n  {col_text}\n);"


def _table_for_index(create_idx: str) -> str | None:
    """Extract the table name from a CREATE INDEX statement."""
    m = re.search(r"ON\s+(\w+)\s*\(", create_idx)
    return m.group(1) if m else None


def _index_columns(create_idx: str) -> list[str]:
    """Extract the indexed column names from a CREATE INDEX statement."""
    m = re.search(r"ON\s+\w+\s*\(([^)]+)\)", create_idx)
    if not m:
        return []
    return [c.strip() for c in m.group(1).split(",")]


def _index_valid_for_d1(stmt: str) -> bool:
    """Check that all columns referenced by an index exist in the D1 schema for that table."""
    table = _table_for_index(stmt)
    if not table:
        return False
    cols = _D1_COLUMNS.get(table)
    if cols is None:
        return True  # Full table synced — all columns available
    # D1 subset: also include "id" since AUTOINCREMENT PKs are kept
    d1_cols = set(cols) | {"id"}
    return all(c in d1_cols for c in _index_columns(stmt))


# ── Main ───────────────────────────────────────────────────────────────────────


def main() -> None:
    synced = set(TABLES_TO_SYNC)

    # Parse and filter tables
    tables = _parse_create_blocks(_TABLES, "TABLE")
    kept_tables = [(name, _slim_table(name, stmt)) for name, stmt in tables if name in synced]

    # Parse and filter indexes (keep only those on synced tables with valid columns)
    indexes = _parse_create_blocks(_INDEXES, "INDEX")
    kept_indexes = [
        (name, stmt) for name, stmt in indexes if _table_for_index(stmt) in synced and _index_valid_for_d1(stmt)
    ]

    # Read existing views from current schema.sql
    views_section = ""
    if _SCHEMA_PATH.exists():
        text = _SCHEMA_PATH.read_text(encoding="utf-8")
        marker_pos = text.find(_VIEWS_MARKER)
        if marker_pos != -1:
            views_section = text[marker_pos:]

    # Assemble output
    parts: list[str] = [_HEADER]

    parts.append("-- ── Tables ────────────────────────────────────────────────────────────────────\n")
    for _name, stmt in kept_tables:
        parts.append(stmt)
        parts.append("")

    parts.append("-- ── Indexes ───────────────────────────────────────────────────────────────────\n")
    for _name, stmt in kept_indexes:
        parts.append(stmt)
    parts.append("")

    # sync_meta is D1-only (not in local DB) — always include
    parts.append("-- Sync metadata (last_sync timestamp, data coverage)")
    parts.append("CREATE TABLE IF NOT EXISTS sync_meta (")
    parts.append("    key   TEXT PRIMARY KEY,")
    parts.append("    value TEXT NOT NULL")
    parts.append(");")
    parts.append("")

    if views_section:
        # Views are maintained manually — append as-is
        parts.append(views_section.rstrip())
        parts.append("")
    else:
        parts.append("-- ── camelCase views (match TypeScript type contract) ──────────────────────────")
        parts.append("-- Views are maintained manually. Add/edit below this line.")
        parts.append("")

    output = "\n".join(parts)
    _SCHEMA_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {_SCHEMA_PATH} ({len(kept_tables)} tables, {len(kept_indexes)} indexes)")


if __name__ == "__main__":
    main()
