"""Generate worker/schema.sql DDL from db.py — tables, indexes, and views.

The generator owns every line of worker/schema.sql: tables and indexes come
from _TABLES/_INDEXES (after slimming to the D1 column subset), and views
come verbatim from _VIEWS in db.py. No hand-edits are preserved.

Usage:
    cd pipeline && python scripts/gen_schema_sql.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Allow importing from the pipeline package
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from generate_asset_snapshot.db import _INDEXES, _TABLES, _VIEWS  # noqa: E402, I001
from scripts.sync_to_d1 import TABLES_TO_SYNC, _D1_COLUMNS  # noqa: E402, I001

# ── Configuration ──────────────────────────────────────────────────────────────

_SCHEMA_PATH = Path(__file__).resolve().parent.parent.parent / "worker" / "schema.sql"

_HEADER = """\
-- D1 schema for portal-api Worker
-- Auto-generated by pipeline/scripts/gen_schema_sql.py — do not edit by hand.
-- Tables/indexes come from db.py; views come from db.py._VIEWS.
-- Views expose camelCase column names matching the TypeScript type contract.
"""

# ── Helpers ────────────────────────────────────────────────────────────────────


def _parse_create_blocks(ddl: str, keyword: str) -> list[tuple[str, str]]:
    """Split a DDL string into (object_name, full_statement) pairs.

    keyword should be 'TABLE' or 'INDEX'.
    """
    # Match CREATE TABLE/INDEX ... (...); or CREATE INDEX ... ON ...;
    pattern = rf"(CREATE\s+{keyword}\s+IF\s+NOT\s+EXISTS\s+(\w+)\s*(?:\([\s\S]*?\)|ON\s+\w+\([^)]*\))\s*;)"
    return [(m.group(2), m.group(1)) for m in re.finditer(pattern, ddl)]


def _slim_table(name: str, create_stmt: str) -> str:
    """If D1 only syncs a column subset for this table, rewrite the CREATE to match."""
    cols = _D1_COLUMNS.get(name)
    if cols is None:
        return create_stmt

    # Extract the column block between the outer parens
    m = re.search(r"\(([\s\S]+)\)", create_stmt)
    if not m:
        return create_stmt

    col_block = m.group(1)
    lines = [line.strip().rstrip(",") for line in col_block.strip().split("\n") if line.strip()]

    kept: list[str] = []
    for line in lines:
        # Check for PRIMARY KEY constraint before column matching
        if line.upper().startswith("PRIMARY KEY"):
            pk_cols_m = re.search(r"\(([^)]+)\)", line)
            if pk_cols_m:
                pk_cols = [c.strip() for c in pk_cols_m.group(1).split(",")]
                if all(c in cols or c == "id" for c in pk_cols):
                    kept.append(line)
            continue
        col_match = re.match(r"(\w+)\s", line)
        if not col_match:
            continue
        col_name = col_match.group(1)
        if col_name == "id" or col_name in cols:
            kept.append(line)

    # Build the new CREATE TABLE
    col_text = ",\n  ".join(kept)
    return f"CREATE TABLE IF NOT EXISTS {name} (\n  {col_text}\n);"


def _table_for_index(create_idx: str) -> str | None:
    """Extract the table name from a CREATE INDEX statement."""
    m = re.search(r"ON\s+(\w+)\s*\(", create_idx)
    return m.group(1) if m else None


def _index_columns(create_idx: str) -> list[str]:
    """Extract the indexed column names from a CREATE INDEX statement."""
    m = re.search(r"ON\s+\w+\s*\(([^)]+)\)", create_idx)
    if not m:
        return []
    return [c.strip() for c in m.group(1).split(",")]


def _index_valid_for_d1(stmt: str) -> bool:
    """Check that all columns referenced by an index exist in the D1 schema for that table."""
    table = _table_for_index(stmt)
    if not table:
        return False
    cols = _D1_COLUMNS.get(table)
    if cols is None:
        return True  # Full table synced — all columns available
    # D1 subset: also include "id" since AUTOINCREMENT PKs are kept
    d1_cols = set(cols) | {"id"}
    return all(c in d1_cols for c in _index_columns(stmt))


# ── Main ───────────────────────────────────────────────────────────────────────


def main() -> None:
    synced = set(TABLES_TO_SYNC)

    # Parse and filter tables
    tables = _parse_create_blocks(_TABLES, "TABLE")
    kept_tables = [(name, _slim_table(name, stmt)) for name, stmt in tables if name in synced]

    # Parse and filter indexes (keep only those on synced tables with valid columns)
    indexes = _parse_create_blocks(_INDEXES, "INDEX")
    kept_indexes = [
        (name, stmt) for name, stmt in indexes if _table_for_index(stmt) in synced and _index_valid_for_d1(stmt)
    ]

    # Assemble output
    parts: list[str] = [_HEADER]

    parts.append("-- ── Tables ────────────────────────────────────────────────────────────────────\n")
    for _name, stmt in kept_tables:
        parts.append(stmt)
        parts.append("")

    parts.append("-- ── Indexes ───────────────────────────────────────────────────────────────────\n")
    for _name, stmt in kept_indexes:
        parts.append(stmt)
    parts.append("")

    # sync_meta is D1-only (not in local DB) — always include
    parts.append("-- Sync metadata (last_sync timestamp, data coverage)")
    parts.append("CREATE TABLE IF NOT EXISTS sync_meta (")
    parts.append("    key   TEXT PRIMARY KEY,")
    parts.append("    value TEXT NOT NULL")
    parts.append(");")
    parts.append("")

    parts.append("-- ── camelCase views (match TypeScript type contract) ──────────────────────────")
    parts.append("")
    for _name, view_sql in _VIEWS.items():
        parts.append(view_sql)
        parts.append("")

    output = "\n".join(parts).rstrip() + "\n"
    _SCHEMA_PATH.write_text(output, encoding="utf-8")
    print(
        f"Wrote {_SCHEMA_PATH} ({len(kept_tables)} tables, "
        f"{len(kept_indexes)} indexes, {len(_VIEWS)} views)"
    )


if __name__ == "__main__":
    main()
