// Auto-generated by pipeline/tools/gen_zod.py from pipeline/etl/types.py.
// DO NOT EDIT BY HAND — rerun the generator to update.

import { z } from "zod";

export const TickerDetailSchema = z.object({
  ticker: z.string(),
  value: z.number(),
  category: z.string(),
  subtype: z.string(),
  costBasis: z.number(),
  gainLoss: z.number(),
  gainLossPct: z.number(),
});

export type TickerDetail = z.infer<typeof TickerDetailSchema>;

export const AllocationRowSchema = z.object({
  date: z.string(),
  total: z.number(),
  usEquity: z.number(),
  nonUsEquity: z.number(),
  crypto: z.number(),
  safeNet: z.number(),
  liabilities: z.number(),
  tickers: z.array(TickerDetailSchema),
});

export type AllocationRow = z.infer<typeof AllocationRowSchema>;

export const FidelityTxnSchema = z.object({
  runDate: z.string(),
  actionType: z.string(),
  symbol: z.string(),
  amount: z.number(),
  quantity: z.number(),
  price: z.number(),
});

export type FidelityTxn = z.infer<typeof FidelityTxnSchema>;

export const QianjiTxnSchema = z.object({
  date: z.string(),
  type: z.string(),
  category: z.string(),
  amount: z.number(),
  accountTo: z.string(),
  isRetirement: z.union([z.boolean(), z.number()]).default(false).transform(Boolean),
});

export type QianjiTxn = z.infer<typeof QianjiTxnSchema>;

export const RobinhoodTxnSchema = z.object({
  txnDate: z.string(),
  action: z.string(),
  actionKind: z.string(),
  ticker: z.string(),
  quantity: z.number(),
  amountUsd: z.number(),
  rawDescription: z.string(),
});

export type RobinhoodTxn = z.infer<typeof RobinhoodTxnSchema>;

export const EmpowerContributionSchema = z.object({
  date: z.string(),
  amount: z.number(),
  ticker: z.string(),
  cusip: z.string(),
});

export type EmpowerContribution = z.infer<typeof EmpowerContributionSchema>;
