-- D1 schema for portal-api Worker
-- Auto-generated by pipeline/scripts/gen_schema_sql.py — do not edit by hand.
-- Tables/indexes come from db.py; views come from db.py._VIEWS.
-- Views expose camelCase column names matching the TypeScript type contract.

-- ── Tables ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS fidelity_transactions (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  run_date        TEXT NOT NULL,
  action_type     TEXT NOT NULL DEFAULT '',
  symbol          TEXT NOT NULL DEFAULT '',
  quantity        REAL NOT NULL DEFAULT 0,
  price           REAL NOT NULL DEFAULT 0,
  amount          REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS daily_close (
  symbol TEXT NOT NULL,
  date   TEXT NOT NULL,
  close  REAL NOT NULL,
  PRIMARY KEY (symbol, date)
);

CREATE TABLE IF NOT EXISTS qianji_transactions (
  date     TEXT NOT NULL,
  type     TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '',
  amount   REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS computed_daily (
    date          TEXT PRIMARY KEY,
    total         REAL NOT NULL,
    us_equity     REAL NOT NULL,
    non_us_equity REAL NOT NULL,
    crypto        REAL NOT NULL,
    safe_net      REAL NOT NULL,
    liabilities   REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS computed_daily_tickers (
    date          TEXT NOT NULL,
    ticker        TEXT NOT NULL,
    value         REAL NOT NULL,
    category      TEXT NOT NULL DEFAULT '',
    subtype       TEXT NOT NULL DEFAULT '',
    cost_basis    REAL NOT NULL DEFAULT 0,
    gain_loss     REAL NOT NULL DEFAULT 0,
    gain_loss_pct REAL NOT NULL DEFAULT 0,
    PRIMARY KEY (date, ticker)
);

CREATE TABLE IF NOT EXISTS computed_market_indices (
    ticker       TEXT PRIMARY KEY,
    name         TEXT NOT NULL DEFAULT '',
    current      REAL NOT NULL DEFAULT 0,
    month_return REAL NOT NULL DEFAULT 0,
    ytd_return   REAL NOT NULL DEFAULT 0,
    high_52w     REAL NOT NULL DEFAULT 0,
    low_52w      REAL NOT NULL DEFAULT 0,
    sparkline    TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS computed_market_indicators (
    key   TEXT PRIMARY KEY,
    value REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS computed_holdings_detail (
    ticker       TEXT PRIMARY KEY,
    month_return REAL NOT NULL DEFAULT 0,
    start_value  REAL NOT NULL DEFAULT 0,
    end_value    REAL NOT NULL DEFAULT 0,
    high_52w     REAL,
    low_52w      REAL,
    vs_high      REAL
);

CREATE TABLE IF NOT EXISTS econ_series (
    key   TEXT NOT NULL,
    date  TEXT NOT NULL,
    value REAL NOT NULL,
    PRIMARY KEY (key, date)
);

CREATE TABLE IF NOT EXISTS categories (
    key           TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    target_pct    REAL NOT NULL DEFAULT 0
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_fidelity_date     ON fidelity_transactions(run_date);
CREATE INDEX IF NOT EXISTS idx_daily_close_date  ON daily_close(date);
CREATE INDEX IF NOT EXISTS idx_daily_tickers_date ON computed_daily_tickers(date);
CREATE INDEX IF NOT EXISTS idx_qianji_txn_date ON qianji_transactions(date);
CREATE INDEX IF NOT EXISTS idx_econ_series_key ON econ_series(key);

-- Sync metadata (last_sync timestamp, data coverage)
CREATE TABLE IF NOT EXISTS sync_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- ── camelCase views (match TypeScript type contract) ──────────────────────────

CREATE VIEW IF NOT EXISTS v_daily AS
SELECT date, total, us_equity AS usEquity, non_us_equity AS nonUsEquity,
  crypto, safe_net AS safeNet, liabilities
FROM computed_daily ORDER BY date;

CREATE VIEW IF NOT EXISTS v_daily_tickers AS
SELECT date, ticker, value, category, subtype,
  cost_basis AS costBasis, gain_loss AS gainLoss, gain_loss_pct AS gainLossPct
FROM computed_daily_tickers ORDER BY date, value DESC;

CREATE VIEW IF NOT EXISTS v_fidelity_txns AS
SELECT run_date AS runDate, action_type AS actionType, symbol, amount,
  quantity, price
FROM fidelity_transactions ORDER BY id;

CREATE VIEW IF NOT EXISTS v_qianji_txns AS
SELECT date, type, category, amount
FROM qianji_transactions ORDER BY date;

CREATE VIEW IF NOT EXISTS v_market_indices AS
SELECT ticker, name, current, month_return AS monthReturn,
  ytd_return AS ytdReturn, high_52w AS high52w, low_52w AS low52w, sparkline
FROM computed_market_indices ORDER BY ticker;

CREATE VIEW IF NOT EXISTS v_market_indicators AS
SELECT key, value FROM computed_market_indicators;

CREATE VIEW IF NOT EXISTS v_market_meta AS
SELECT
  MAX(CASE WHEN key = 'fedRate' THEN value END) AS fedRate,
  MAX(CASE WHEN key = 'treasury10y' THEN value END) AS treasury10y,
  MAX(CASE WHEN key = 'cpi' THEN value END) AS cpi,
  MAX(CASE WHEN key = 'unemployment' THEN value END) AS unemployment,
  MAX(CASE WHEN key = 'vix' THEN value END) AS vix,
  MAX(CASE WHEN key = 'dxy' THEN value END) AS dxy,
  MAX(CASE WHEN key = 'usdCny' THEN value END) AS usdCny
FROM computed_market_indicators;

CREATE VIEW IF NOT EXISTS v_holdings_detail AS
SELECT ticker, month_return AS monthReturn, start_value AS startValue,
  end_value AS endValue, high_52w AS high52w, low_52w AS low52w, vs_high AS vsHigh
FROM computed_holdings_detail ORDER BY month_return DESC;

CREATE VIEW IF NOT EXISTS v_econ_series AS
SELECT key, date, value FROM econ_series ORDER BY key, date;

CREATE VIEW IF NOT EXISTS v_econ_series_grouped AS
SELECT key,
  json_group_array(json_object('date', date, 'value', value)) AS points
FROM (SELECT key, date, value FROM econ_series ORDER BY key, date)
GROUP BY key ORDER BY key;

CREATE VIEW IF NOT EXISTS v_econ_snapshot AS
SELECT key, value
FROM econ_series t1
WHERE date = (SELECT MAX(date) FROM econ_series t2 WHERE t2.key = t1.key);

CREATE VIEW IF NOT EXISTS v_categories AS
SELECT key, name,
  display_order AS displayOrder,
  target_pct AS targetPct
FROM categories ORDER BY display_order;
